name: arimax-llm
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - bottleneck=1.4.2=py310h03d0aa3_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - expat=2.7.1=h313beb8_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.30=hf2bb037_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - ncurses=6.5=hee39554_0
  - numexpr=2.11.0=py310h8c72970_1
  - numpy=2.2.5=py310h40d09ce_2
  - numpy-base=2.2.5=py310h855c928_2
  - openssl=3.0.18=h9b4081a_0
  - pandas=2.3.3=py310hc6ded6b_0
  - pip=25.2=pyhc872135_1
  - python=3.10.19=hf701271_0
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py310hca03da5_0
  - readline=8.3=h0b18652_0
  - scipy=1.15.3=py310h132fc3c_1
  - setuptools=80.9.0=py310hca03da5_0
  - six=1.17.0=py310hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - arch==8.0.0
      - beautifulsoup4==4.14.2
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - contourpy==1.3.2
      - curl-cffi==0.13.0
      - cycler==0.12.1
      - filelock==3.20.0
      - fonttools==4.60.1
      - frozendict==2.4.6
      - fsspec==2025.10.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multitasking==0.0.12
      - networkx==3.4.2
      - packaging==25.0
      - patsy==1.0.2
      - peewee==3.18.2
      - pillow==12.0.0
      - platformdirs==4.5.0
      - protobuf==6.33.0
      - pycparser==2.23
      - pyparsing==3.2.5
      - pyyaml==6.0.3
      - regex==2025.10.23
      - requests==2.32.5
      - safetensors==0.6.2
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - soupsieve==2.8
      - statsmodels==0.14.5
      - sympy==1.14.0
      - tokenizers==0.22.1
      - torch==2.9.0
      - tqdm==4.67.1
      - transformers==4.57.1
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - websockets==15.0.1
      - yfinance==0.2.66
prefix: /Users/sazankhalid/miniconda3/envs/arimax-llm
